sudo: required

services:
  - docker

before_install:
  - docker build -t nikolakp/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nikolakp/docker-react-test npm run test -- --coverage

after_success:
  - docker build -t nikolakp/multi-client -f ./client/Dockerfile ./client
  - docker build -t nikolakp/multi-nginx  -f ./nginx/Dockerfile ./nginx
  - docker build -t nikolakp/multi-server -f ./server/Dockerfile ./server
  - docker build -t nikolakp/multi-worker -f ./worker/Dockerfile ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nikolakp/multi-client
  - docker push nikolakp/multi-nginx
  - docker push nikolakp/multi-server
  - docker push nikolakp/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-306476627547
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_kEY
    secret_access_key:
      secure: $AWS_SECRET_KEY  